---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
activity <- read.csv("C:/Users/chavezke/Desktop/Coursera/data/activity.csv")
activity$date <- as.Date(activity$date)
library(reshape2)
actMeltDate <- melt(activity, id.vars="date", measure.vars="steps", na.rm=FALSE)
actCastDate <- dcast(actMeltDate, date ~ variable, sum)
plot(actCastDate$date, actCastDate$steps, type="h", main="Histogram of Daily Steps", xlab="Date", ylab="Steps per Day", col="blue", lwd=8)
abline(h=mean(actCastDate$steps, na.rm=TRUE), col="red", lwd=2)
```

## What is mean total number of steps taken per day?
```{r}
mean(actCastDate$steps, na.rm = TRUE)
```
## What is the average daily activity pattern?
```{r}
median(actCastDate$steps, na.rm = TRUE)
```

## Imputing missing values
```{r}
stepsPerInt <- actCastInt
actNoNA <- activity
actMerge = merge(actNoNA, stepsPerInt, by="interval", suffixes=c(".act", ".spi"))
naIndex = which(is.na(actNoNA$steps))
actNoNA[naIndex,"steps"] = actMerge[naIndex,"steps.spi"]
```

## Are there differences in activity patterns between weekdays and weekends?
```{r Combine data by date}
actMeltDateNoNA <- melt(actNoNA, id.vars="date", measure.vars="steps", na.rm=FALSE)
```
```{r Categorize steps by date}
actCastDateNoNA <- dcast(actMeltDateNoNA, date ~ variable, sum)
```

```{r Plot Histogram of Daily Steps}
plot(actCastDateNoNA$date, actCastDateNoNA$steps, type="h", main="Histogram of Daily Steps (Removed NA Values)", xlab="Date", ylab="Steps", col="gray", lwd=8)
abline(h=mean(actCastDateNoNA$steps), col="red", lwd=2)
```

``` {r Daily steps mean}
mean(actCastDateNoNA$steps, na.rm=TRUE)
```

``` {r Daily steps median}
median(actCastDateNoNA$steps, na.rm=TRUE)
```

``` {r Compare weekdays with weekends}
for (i in 1:nrow(actNoNA)) {
  if (weekdays(actNoNA$date[i]) == "Saturday" | weekdays(actNoNA$date[i]) == "Sunday") {
    actNoNA$dayOfWeek[i] = "weekend"
  } else {
    actNoNA$dayOfWeek[i] = "weekday"
  }
}
```

``` {r Combine weekday and Weekend data}
actWeekday <- subset(actNoNA, dayOfWeek=="weekday")
actWeekend <- subset(actNoNA, dayOfWeek=="weekend")
actMeltWeekday <- melt(actWeekday, id.vars="interval", measure.vars="steps")
actMeltWeekend <- melt(actWeekend, id.vars="interval", measure.vars="steps")
actCastWeekday <- dcast(actMeltWeekday, interval ~ variable, mean)
actCastWeekend <- dcast(actMeltWeekend, interval ~ variable, mean)
```

``` {r Load plotting packages}
library(ggplot2)
library(gridExtra)
```

``` {r Plots by interval for weekdays and weekends}
plot1 <- qplot(actCastWeekday$interval, actCastWeekday$steps, geom="line", data=actCastWeekday, main="Steps by Interval - Weekday", xlab="Interval ID", ylab="Number of Steps")
plot2 <- qplot(actCastWeekend$interval, actCastWeekend$steps, geom="line", data=actCastWeekend, main="Steps by Interval - Weekend", xlab="Interval ID", ylab="Number of Steps")
grid.arrange(plot1, plot2, nrow=2)
```
